zuul:
  routes:
    orders:
     url: http://localhost:8090
    messages:
      #path: /messages/*
      #url: forward:/messages
      url: http://localhost:9000

logging:
  level:
    root: INFO

ribbon:
  eureka:
    enabled: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
